layout_spectrum: 0.4808511
color:
  saturation: 0.9905331
  lightness: 0.6760733
  brandStrength: 0.2110204
  rhythmicContrast: 0.7627085
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
typography_spectrum: 0.4216362
name: Film Work
